config/routes.rb
Rails.application.routes.draw do
  

  resources :posts


  devise_for :users

  resources :losts do
    resources :conversations
  end

   resources :profiles do
    resources :conversations
  end


  devise_scope :user do 
    get "cadastrar", to: "devise/registrations#new", as: :cadastrar
  end

  devise_scope :user do 
    get "entrar", to: "devise/sessions#new", as: :entrar
  end

  devise_scope :user do 
    get "sair", to: "devise/sessions#destroy", as: :sair
  end


  root 'posts#index'

  get 'profiles/show'
  
  get "adotar", to: 'posts#index', as: :adotar

  get "posts", to: 'posts#index'
  
  get "/pages/:page" => "pages#show"

  get '/:id', to: 'profiles#show', as: :id do
    resources :conversations
  end

  resources :conversations do
    resources :messages
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    if user_signed_in?
    @users = User.where.not("id = ?",current_user.id).order("created_at DESC")
    @conversations = Conversation.involving(current_user)
    end
  	@user = User.find_by_profile_name(params[:id])
  	if @user 
  		@losts = @user.losts.all
  		@posts = @user.posts.all

  		render action: :show
  	else
  		render file: 'public/404', status: 404, formats: [:html]
  	end
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/show.html.erb
 <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-64755509-1', 'auto');
  ga('send', 'pageview');

</script>

<div class="col-md-3">

<div class="jumbotron" data-spy="affix" id="salve2">
<h6 style="color=#4
}44; padding:0; padding-left:3px;"><strong>PÁGINAS</strong></h6>
<button onclick="location.href='<%= adotar_path %>';" type="submit" class="btn btn-block btn-default" id="msg2"><i class="fa fa-paw" id="i"></i> Adotar</button>
<button onclick="location.href='<%= losts_path %>';" type="submit" class="btn  btn-block btn-default" id="msg2"><i class="fa fa-search" id="i3"></i> Animais perdidos</button>
<button onclick="location.href='<%= new_post_path %>';" type="submit" class="btn  btn-block btn-default" id="msg2"><i class="fa fa-tag " id="i2"></i> Doar</button>
<button onclick="location.href='/pages/campanhas';" type="submit" class="btn  btn-block btn-default" id="msg2"><i class="fa fa-usd" id="i1"></i> Campanhas <span class="label label-warning">Breve</span></button>


<% if user_signed_in? %>
<h6 style="color=#444; padding:0; padding-left:3px;"><strong>CONTA</strong></h6>
<button onclick="location.href='<%= id_path(current_user.profile_name) %>';" type="submit" class="btn btn-block btn-default" id="msg2"><i class="fa fa-user" id="i"></i> Meu perfil</button>
<button onclick="location.href='#';" type="submit" class="btn btn-block btn-default" id="msg2"  data-toggle="modal" data-target="#myModal2"><i class="fa fa-envelope" id="i22"></i> Mensagens</button>
<button onclick="location.href='<%= edit_user_registration_path %>';" type="submit" class="btn  btn-block btn-default" id="msg2"><i class="fa fa-cog" id="i"></i> Editar minha conta</button>
<button onclick="location.href='<%= sair_path %>';" type="submit" class="btn  btn-block btn-default" id="msg2"><i class="fa fa-sign-out" id="i3"></i> Sair</button>

<h6>Logado como <%= current_user.name %></h6>


<% else %>

<div id="ladoentrar2">
  <div class="actions">
    <button onclick="location.href='<%= entrar_path %>';" type="submit" class="btn btn-success btn-block btn-primary" id="msg">Entrar</button>
  </div>
</div>


<div id="ladoentrar">
<%= simple_form_for(:user, :defaults => { :input_html => { :class => "form-control" } }, as: resource_name, url: session_path(:user)) do |f| %>
 

 <%= f.input :email, label: false, :placeholder => "seu@email.com" %>
 <%= f.input :password, label: false, :placeholder => "senha" %>
  <div class="actions">
    <button type="submit" class="btn btn-success btn-block btn-primary" id="msg">Entrar</button>
  </div>

</div>

<% end %>
<% end %>

<h6 style="text-align:center;"><a href="/pages/ajuda">Dúvidas</a> | <a href="/pages/contato">Contato</a> | <a href="/pages/termos2">Termos</a></h6>



</div>

</div>

<div class="col-md-9">

<div class="jumbotron" id="ficarmenor3">
  
	<fieldset>
      <table width="100%" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td width="12%" align="left"><img src="/default.png"></td>
        <td align="left"><div id="info">
    <legend id="riscosempadd"><h2><%= @user.name %> 

      <% if user_signed_in? %>
        <% if current_user.profile_name.to_str == @user.profile_name.to_str %>
        <%= link_to 'Fazer uma nova doação', new_post_path, :class => "btn btn-primary", :id => "msg" %> <a id="msg" class="btn btn-warning" href="<%= edit_user_registration_path %>">Editar conta</a>
        <% else %>
        <a  id="msg" data-placement="bottom" href="" data-sid="<%= current_user.id %>", data-rip="<%= @user.id %>" class="btn btn-success start-conversation">Enviar mensagem</a></h5>
        <% end %>
    <% else %>
        <button id="msg" class="btn btn-success" data-toggle="popover" data-trigger="focus" title="Aviso!" data-content="Você precisa se <a href='<%= cadastrar_path %>'>Cadastrar</a> ou <a href='<%= entrar_path %>'>Logar</a> para usar o Chat." data-placement="bottom" data-html="true" tabindex="0" >Enviar mensagem</button>
    <% end %>

    </h2></legend>
    <h5>Perfil com animais e contatos de <strong><%= @user.name%></strong>.</h5>
    <h5><strong>Email: </strong><%= @user.email %></h5>
    </div></td>
      </tr>
    </table>
		
	</fieldset>
</div>

<div class="row">
  


<% if @posts %>
	<% @posts.each do |post| %>

    <div class="col-sm-6 col-md-4">
      <div class="jumbotron" id="quebragalho">
      <h4><strong><%= link_to post.name.upcase, post, :id => "nomeanimal" %></strong></h4>
      <% if post.image %>
      <%= image_tag post.image.url(:thumb), :class => "fotoperfil" %>
      <% end %>
      <% if user_signed_in? %>
        <% if current_user.profile_name.to_str == post.user.profile_name.to_str %>
        <div class="alert alert-warning alert-dismissible fade in" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
      <strong><i class="fa fa-exclamation-circle fa-lg"></i></strong> Se seu animal ja foi doado clique em <strong>apagar</strong> para retirar o post, obrigado.
    </div>
            <h6><%= link_to ' Editar', edit_post_path(post), :class => "btn btn-xs btn-primary" %>  <%= link_to ' Apagar', post, method: :delete, data: { confirm: 'Você tem certeza de que quer apagar? Não tem como desfazer depois!' }, :class => "btn btn-xs btn-danger" %></h6>
        <% end %>
      <% end %>
       
       </div>
     </div>
    <% end %>
 
</div>
<% end %>

<% if @posts.count == 0 %>

<div class="alert alert-warning alert-dismissible fade in" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
      <h6>Nenhum animal para doação nesse perfil.</h6>
    </div>
<% end %>
 
</div>

<% if user_signed_in? %>
<!-- Modal -->
<div class="modal fade" id="myModal2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title" id="myModalLabel"><i class="fa fa-comments"></i> Mensagens <%= link_to "Atualizar", adotar_path, :method => :get, class: "btn btn-success btn-xs start-conversation" %></h3>
      </div>
      <div class="modal-body">
        
        <% if @conversations.any? %>
          <ul class="media-list">
            <% @conversations.each do |conversation| %>
                <li class="media">
                  <%= image_tag("/default.png", class: "media-object pull-left") %>
                  <div class="media-body">
                    <%= link_to "", conversation_path(conversation), class: "conversation", "data-cid" => conversation.id, "data-toggle" => "modal", "data-target" => "#myModal2" %>
                        <h4 class="media-heading"><%= conversation_interlocutor(conversation).name %></h4>
                        <p>> <%= conversation.messages.last.nil? ? "No messages" : truncate(conversation.messages.last.body, length: 45) %></p>
                  </div>
                  <legend></legend>
                </li>

            <% end %>
          </ul>
      <% else %>
          <p>Nenhuma mensagem encontrada.</p>
      <% end %>

      </div>
    </div>
  </div>
</div>

<% end %>