config/routes.rb
Rails.application.routes.draw do
  

  resources :posts


  devise_for :users

  resources :losts do
    resources :conversations
  end

   resources :profiles do
    resources :conversations
  end


  devise_scope :user do 
    get "cadastrar", to: "devise/registrations#new", as: :cadastrar
  end

  devise_scope :user do 
    get "entrar", to: "devise/sessions#new", as: :entrar
  end

  devise_scope :user do 
    get "sair", to: "devise/sessions#destroy", as: :sair
  end


  root 'posts#index'

  get 'profiles/show'
  
  get "adotar", to: 'posts#index', as: :adotar

  get "posts", to: 'posts#index'
  
  get "/pages/:page" => "pages#show"

  get '/:id', to: 'profiles#show', as: :id do
    resources :conversations
  end

  resources :conversations do
    resources :messages
  end

end

app/models/lost.rb
class Lost < ActiveRecord::Base
	 belongs_to :user 
   has_many :comments

  has_attached_file :photo, :styles => {:thumb => "242x200#"}
  validates_attachment_content_type :photo, content_type: %w(image/jpeg image/jpg image/png)



    validates :name, presence: true
    validates :animal, presence: true
    validates :gender, presence: true
    validates :size, presence: true
    validates :about, presence: true
    validates :bairro, presence: true
    validates :date, presence: true
    validates :city, presence: true
    validates :phone, presence: true
    validates :user_id, presence: true
    validates :photo, :attachment_presence => true

end

app/controllers/losts_controller.rb
class LostsController < ApplicationController
  before_action :set_lost, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  # GET /losts
  # GET /losts.json
  def index
    if user_signed_in?
    @users = User.where.not("id = ?",current_user.id).order("created_at DESC")
    @conversations = Conversation.involving(current_user)
    end
    
    @losts = Lost.all
  end

  # GET /losts/1
  # GET /losts/1.json
  def show
         @meta = { title: 'PROCURA-SE ! '+@lost.name.downcase.capitalize+' em '+@lost.city.downcase.capitalize+'.', description: @lost.about, image: 'http://encontrepet.com'+@lost.photo.url(:thumb), type: 'article' }
  end

  # GET /losts/new
  def new
    @lost = current_user.losts.new
  end

  # GET /losts/1/edit
  def edit
  end

  # POST /losts
  # POST /losts.json
  def create
    @lost = current_user.losts.new(lost_params)
    respond_to do |format|
      if @lost.save
        format.html { redirect_to @lost, notice: 'Animal desaparecido foi publicado com sucesso.' }
        format.json { render :show, status: :created, location: @lost }
      else
        format.html { render :new }
        format.json { render json: @lost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /losts/1
  # PATCH/PUT /losts/1.json
  def update
    @lost = current_user.losts.find(params[:id])
    respond_to do |format|
      if @lost.update(lost_params)
        format.html { redirect_to @lost, notice: 'Lost was successfully updated.' }
        format.json { render :show, status: :ok, location: @lost }
      else
        format.html { render :edit }
        format.json { render json: @lost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /losts/1
  # DELETE /losts/1.json
  def destroy
    @lost.destroy
    respond_to do |format|
      format.html { redirect_to losts_url, notice: 'Lost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lost
      @lost = Lost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lost_params
      params.require(:lost).permit(:comment, :photo, :user_id, :name, :animal, :gender, :size, :about, :city, :bairro, :date, :phone, :another_phone)
    end
end

app/helpers/losts_helper.rb
module LostsHelper
  
  def conversation_interlocutor(conversation)
    conversation.recipient == current_user ? conversation.sender : conversation.recipient
  end


end

app/views/losts/_form.html.erb
<div class="jumbotron" id="ficarmenor2">
<%= simple_form_for(@lost, html: {multipart: true}) do |f| %>
  <h3 id="entrar2">Informações do animal desaparecido :</h3>
</br >
  <div class="form-inputs">
    <%= f.input :name, label: "Nome do animal:" %>
    <%= f.input :animal, label: "Animal:", :as => :select, :collection => [['Cachorro', :Cachorro], ['Gato', :Gato], ['Outro', :Outro]] %>
    <%= f.input :gender, label: "Gênero:", :as => :select, :collection => [['Macho', :Macho], ['Fêmea', :Fêmea]], label: "Gênero :"  %>
    <%= f.input :size, label: "Tamanho:", :as => :select, :collection => [['Pequeno', :Pequeno], ['Médio', :Médio], ['Grande', :Grande]] %>
    <%= f.input :about, label: "Sobre:", placeholder: 'Descreva as características do animal e o local onde ocorreu o desaparecimento.' %>
    <div class="well">
<%= f.input :photo, as: :file, label: "Foto do animal:" %>
</div>
    <%= f.input :city, label: "Cidade :", placeholder: 'Cidade e Estado', :as => :select, :collection => [['Curitiba - PR', :'Curitiba - PR'],

['Alagoas – Maceió', :'Alagoas – Maceió'],
['Amapá – Macapá', :'Amapá – Macapá'],
['Amazonas – Manaus', :'Amazonas – Manaus'],
['Bahia – Salvador', :'Bahia – Salvador'],
['Ceará – Fortaleza', :'Ceará – Fortaleza'],
['Distrito Federal – Brasília', :'Distrito Federal – Brasília'],
['Espírito Santo – Vitória', :'Espírito Santo – Vitória'],
['Goiás – Goiânia', :'Goiás – Goiânia'],
['Maranhão – São Luís', :'Maranhão – São Luís'],
['Mato Grosso – Cuiabá', :'Mato Grosso – Cuiabá'],
['Mato Grosso do Sul – Campo Grande', :'Mato Grosso do Sul – Campo Grande'],
['Minas Gerais – Belo Horizonte', :'Minas Gerais – Belo Horizonte'],
['Pará – Belém', :'Pará – Belém'],
['Paraíba – João Pessoa', :'Paraíba – João Pessoa'],
['Pernambuco – Recife', :'Pernambuco – Recife'],
['Piauí – Teresina', :'Piauí – Teresina'],
['Roraima – Boa Vista', :'Roraima – Boa Vista'],
['Rondônia – Porto Velho', :'Rondônia – Porto Velho'],
['Rio de Janeiro – Rio de Janeiro', :'Rio de Janeiro – Rio de Janeiro'],
['Rio Grande do Norte – Natal', :'Rio Grande do Norte – Natal'],
['Rio Grande do Sul – Porto Alegre', :'Rio Grande do Sul – Porto Alegre'],
['Santa Catarina – Florianópolis', :'Santa Catarina – Florianópolis'],
['São Paulo – São Paulo', :'São Paulo – São Paulo'],
['Sergipe – Aracaju', :'Sergipe – Aracaju'],
['Tocantins – Palmas', :'Tocantins – Palmas']] %>

    <%= f.input :bairro, label: "Bairro:", placeholder: 'Bairro do desaparecimento' %>
    <%= f.input :date, label: "Data do desaparecimento:" %>
    <%= f.input :phone, label: "Telefone 1:", placeholder: '(DDD) 0000-0000' %>
    <%= f.input :another_phone, label: "Telefone 2:", placeholder: 'Opcional' %>
  </div>

  <div class="form-actions">
    <button type="submit" class="btn btn-success btn-lg btn-block" id="button" data-loading-text="Enviando..." autocomplete="off">Publicar</button>
    <%= link_to 'Cancelar', losts_path, :class => "btn btn-default btn-block", data: { confirm: 'Você tem certeza ?' } %>
  </div>
<% end %>
</div>

app/views/losts/edit.html.erb
<% if current_user.profile_name.to_str == @lost.user.profile_name.to_str %>
<%= render 'form' %>
<% else %>
<%= render :file => 'public/422.html' %>
<% end %>

app/views/losts/index.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-64755509-1', 'auto');
  ga('send', 'pageview');

</script>

<% if user_signed_in? %>
<!-- Modal -->
<div class="modal fade" id="myModal2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title" id="myModalLabel"><i class="fa fa-comments"></i> Mensagens <%= link_to "Atualizar", adotar_path, :method => :get, class: "btn btn-success btn-xs start-conversation" %></h3>
      </div>
      <div class="modal-body">
        
        <% if @conversations.any? %>
          <ul class="media-list">
            <% @conversations.each do |conversation| %>
                <li class="media">
                  <%= image_tag("/default.png", class: "media-object pull-left") %>
                  <div class="media-body">
                    <%= link_to "", conversation_path(conversation), class: "conversation", "data-cid" => conversation.id, "data-toggle" => "modal", "data-target" => "#myModal2" %>
                        <h4 class="media-heading"><%= conversation_interlocutor(conversation).name %></h4>
                        <p>> <%= conversation.messages.last.nil? ? "No messages" : truncate(conversation.messages.last.body, length: 45) %></p>
                  </div>
                  <legend></legend>
                </li>

            <% end %>
          </ul>
      <% else %>
          <p>Nenhuma mensagem encontrada.</p>
      <% end %>

      </div>
    </div>
  </div>
</div>

<% end %>

<div class="col-md-3">

<div class="jumbotron" data-spy="affix" id="salve2">
<h6 style="color=#4
}44; padding:0; padding-left:3px;"><strong>PÁGINAS</strong></h6>
<button onclick="location.href='<%= adotar_path %>';" type="submit" class="btn btn-block btn-default " id="msg2"><i class="fa fa-paw" id="i"></i> Adotar</button>
<button onclick="location.href='<%= losts_path %>';" type="submit" class="btn  btn-block btn-default active" id="msg2"><i class="fa fa-search" id="i3"></i> Animais perdidos</button>
<button onclick="location.href='<%= new_post_path %>';" type="submit" class="btn  btn-block btn-default" id="msg2"><i class="fa fa-tag " id="i2"></i> Doar</button>
<button onclick="location.href='/pages/campanhas';" type="submit" class="btn  btn-block btn-default" id="msg2"><i class="fa fa-usd" id="i1"></i> Campanhas <span class="label label-warning">Breve</span></button>


<% if user_signed_in? %>
<h6 style="color=#444; padding:0; padding-left:3px;"><strong>CONTA</strong></h6>
<button onclick="location.href='<%= id_path(current_user.profile_name) %>';" type="submit" class="btn btn-block btn-default" id="msg2"><i class="fa fa-user" id="i"></i> Meu perfil</button>
<button onclick="location.href='#';" type="submit" class="btn btn-block btn-default" id="msg2"  data-toggle="modal" data-target="#myModal2"><i class="fa fa-envelope" id="i22"></i> Mensagens</button>
<button onclick="location.href='<%= edit_user_registration_path %>';" type="submit" class="btn  btn-block btn-default" id="msg2"><i class="fa fa-cog" id="i"></i> Editar minha conta</button>
<button onclick="location.href='<%= sair_path %>';" type="submit" class="btn  btn-block btn-default" id="msg2"><i class="fa fa-sign-out" id="i3"></i> Sair</button>

<h6>Logado como <%= current_user.name %></h6>


<% else %>


<div id="ladoentrar2">
  <div class="actions">
    <button onclick="location.href='<%= entrar_path %>';" type="submit" class="btn btn-success btn-block btn-primary" id="msg">Entrar</button>
  </div>
 <h6><a href="/cadastrar">Criar uma conta</a></h6>
</div>


<div id="ladoentrar">
<%= simple_form_for(:user, :defaults => { :input_html => { :class => "form-control" } }, as: resource_name, url: session_path(:user)) do |f| %>
 

 <%= f.input :email, label: false, :placeholder => "seu@email.com" %>
 <%= f.input :password, label: false, :placeholder => "senha" %>
  <div class="actions">
    <button type="submit" class="btn btn-success btn-block btn-primary" id="msg">Entrar</button>
  </div>

</div>

<% end %>
<% end %>

<h6 style="text-align:center;"><a href="/pages/ajuda">Dúvidas</a> | <a href="/pages/contato">Contato</a> | <a href="/pages/termos2">Termos</a></h6>



</div>

</div>

<div class="col-md-9">





<div class="jumbotron" id="salve">
  <div id="comodoar">
    <h4><strong>Dica:</strong></h4>
  </div>
  

<a href="<%= new_lost_path %>"><img id="fala" src="/FALA3.png"></a>
  </div>

</br >



<div id="cards">
<div class="row">

 
<% @losts.each do |lost| %>
   <div class="col-sm-6 col-md-4">

    <div class="thumbnail" id="animal">
      <h2 id="entrar2"><%= lost.name %></h2>
      <% if lost.photo %>
      <%= image_tag lost.photo.url(:thumb), onerror: "this.src='/default_photo.png'", :id => "foto_ficha2" %>
      <% end %>

      </br>
      

      <div class"final" id="cor">
     
        <% if user_signed_in? %>
      <h5> <%= link_to "Ver informações", lost , :class => "btn btn-primary ", :id => "msg" %>  
        <a id="msg" data-tooltip="tooltip" data-placement="bottom" title="Enviar mensagem" href="" data-sid="<%= current_user.id %>", data-rip="<%= lost.user.id %>" class="btn btn-success start-conversation">Chat <i class="fa fa-comments"></i></a></h5>
      <% else %>
      <h5> <%= link_to "Ver informações", lost , :class => "btn btn-primary ", :id => "msg" %> 
        
        <a id="msg" class="btn btn-success start-conversation" role="button" data-toggle="popover" data-trigger="focus" title="Aviso!" data-content="Você precisa se <a href='<%= cadastrar_path %>'>Cadastrar</a> ou <a href='<%= entrar_path %>'>Logar</a> para usar o Chat." data-placement="bottom" data-html="true" tabindex="0" >Chat <i class="fa fa-comments"></i></a></h5>
      <% end %>
      

    </div>



 

</div>
 </div>
    <% end %>
</div>
</div>

<% if @losts.count == 0 %>
<h4 id="comodoar3"><strong><i class="fa fa-thumbs-o-up fa-2x"></i> Nenhum animal perdido publicado!</strong></h4>
<% end %>



</div>

app/views/losts/new.html.erb
<%= render 'form' %>

app/views/losts/show.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-64755509-1', 'auto');
  ga('send', 'pageview');

</script>



<div class="col-md-3">

<div class="jumbotron" data-spy="affix" id="salve2">
<h6 style="color=#4
}44; padding:0; padding-left:3px;"><strong>PÁGINAS</strong></h6>
<button onclick="location.href='<%= adotar_path %>';" type="submit" class="btn btn-block btn-default " id="msg2"><i class="fa fa-paw" id="i"></i> Adotar</button>
<button onclick="location.href='<%= losts_path %>';" type="submit" class="btn  btn-block btn-default active" id="msg2"><i class="fa fa-search" id="i3"></i> Animais perdidos</button>
<button onclick="location.href='<%= new_post_path %>';" type="submit" class="btn  btn-block btn-default" id="msg2"><i class="fa fa-tag " id="i2"></i> Doar</button>
<button onclick="location.href='/pages/campanhas';" type="submit" class="btn  btn-block btn-default" id="msg2"><i class="fa fa-usd" id="i1"></i> Campanhas <span class="label label-warning">Breve</span></button>


<% if user_signed_in? %>
<h6 style="color=#444; padding:0; padding-left:3px;"><strong>CONTA</strong></h6>
<button onclick="location.href='<%= id_path(current_user.profile_name) %>';" type="submit" class="btn btn-block btn-default" id="msg2"><i class="fa fa-user" id="i"></i> Meu perfil</button>
<button onclick="location.href='#';" type="submit" class="btn btn-block btn-default" id="msg2"  data-toggle="modal" data-target="#myModal2"><i class="fa fa-envelope" id="i22"></i> Mensagens</button>
<button onclick="location.href='<%= edit_user_registration_path %>';" type="submit" class="btn  btn-block btn-default" id="msg2"><i class="fa fa-cog" id="i"></i> Editar minha conta</button>
<button onclick="location.href='<%= sair_path %>';" type="submit" class="btn  btn-block btn-default" id="msg2"><i class="fa fa-sign-out" id="i3"></i> Sair</button>

<h6>Logado como <%= current_user.name %></h6>


<% else %>

<div id="ladoentrar2">
  <div class="actions">
    <button onclick="location.href='<%= entrar_path %>';" type="submit" class="btn btn-success btn-block btn-primary" id="msg">Entrar</button>
  </div>
 <h6><a href="/cadastrar">Criar uma conta</a></h6>
</div>


<div id="ladoentrar">
<%= simple_form_for(:user, :defaults => { :input_html => { :class => "form-control" } }, as: resource_name, url: session_path(:user)) do |f| %>
 

 <%= f.input :email, label: false, :placeholder => "seu@email.com" %>
 <%= f.input :password, label: false, :placeholder => "senha" %>
  <div class="actions">
    <button type="submit" class="btn btn-success btn-block btn-primary" id="msg">Entrar</button>
  </div>
</div>

<% end %>
<% end %>

<h6 style="text-align:center;"><a href="/pages/ajuda">Dúvidas</a> | <a href="/pages/contato">Contato</a> | <a href="/pages/termos2">Termos</a></h6>




</div>
</div>

<div class="col-md-5">
<div class="jumbotron" id="ficarmenor2">
<h2 id="entrar2"><%= @lost.name %></h2>
 </br >
  <% if @lost.photo %>
      <%= image_tag @lost.photo.url(:thumb), :id => "foto_ficha" %>
  <% end %> 
</br >
<legend>
  <div id="entrar" class="fb-like" data-href="<%= request.url %>" data-layout="button_count" data-action="like" data-show-faces="true" data-share="true"></div>
</legend>

<legend>
<h5>
  <strong>Dono:</strong>
  <%= link_to @lost.user.name, id_path(@lost.user.profile_name) %>
</h5>
</legend>

<legend>  
<h5>
  <strong>Local:</strong>
  <%= @lost.bairro %> - <%= @lost.city %>
</h5>
</legend>

<legend>
<h5>
  <strong>Data do desaparecimento:</strong>
  <%= @lost.date %>
</h5>
</legend>

<legend>  
<h5>
  <strong>Animal:</strong>
  <%= @lost.animal %>
</h5>
</legend>

<legend>
<h5>
  <strong>Gênero:</strong>
  <%= @lost.gender %>
</h5>
</legend>

<legend>
<h5>
  <strong>Idade:</strong>
  <%= @lost.size %>
</h5>
</legend>

<legend>
<h5>
  <strong>Informações:</strong>
  <%= @lost.about %>
</h5>
</legend>

 <legend>
<h5>
<strong>Foto:</strong>
 <%= lost_foto @lost %>
</h5>
</legend>

<div id="botaofinal">
<button type="button" class="btn btn-success btn-block btn-lg" data-toggle="modal" data-target="#myModal">Contatos</button>
<%= link_to 'Voltar', losts_path, :class => "btn btn-default btn-block" %>
     
      <% if user_signed_in? %>
        <div class="footer">
          <span class="admin">
          <% if current_user.profile_name.to_str == @lost.user.profile_name.to_str %>
            <h6><%= link_to ' Editar', edit_lost_path(@lost), :class => "btn btn-xs btn-primary" %>  <%= link_to ' Apagar', @lost, method: :delete, data: { confirm: 'Você tem certeza de que quer apagar? Não tem como desfazer depois!' }, :class => "btn btn-xs btn-danger" %></h6>
          <% else %>
          <% end %>
          </span>
        </div> 
      <% else %>
      <% end %>
<div class="modal fade in" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Contatos dono(a) de <strong><%=  @lost.name %></strong> :</h4>
      </div>
      <div class="modal-body">
      <h5><strong>Telefone 1:</strong> <a href="tel:<%= @lost.phone %>"><%= @lost.phone %></a></h5>
      <h5><strong>Telefone 2:</strong> <a href="tel:<%= @lost.another_phone %>"><%= @lost.another_phone %></a></h5>
      <h5><strong>E-mail:</strong> <a href="mailto:<%= @lost.user.email %>"><%= @lost.user.email %></a></h5>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-success" data-dismiss="modal">OK</button>
      </div>
    </div>
  </div>
</div>
</div>


</div>
</div>

<div class="col-md-4">
  <div class="jumbotron" id="ficarmenor4">
    <h4 id="entrar3"><i class="fa fa-comments fa-lg"></i> COMENTÁRIOS</h4>

    <div class="fb-comments" data-href="<%= request.url %>" data-width="289" data-numposts="5"></div>

            

</div>
</div>
</div>