config/routes.rb
Rails.application.routes.draw do
  

  resources :posts


  devise_for :users

  resources :losts do
    resources :conversations
  end

   resources :profiles do
    resources :conversations
  end


  devise_scope :user do 
    get "cadastrar", to: "devise/registrations#new", as: :cadastrar
  end

  devise_scope :user do 
    get "entrar", to: "devise/sessions#new", as: :entrar
  end

  devise_scope :user do 
    get "sair", to: "devise/sessions#destroy", as: :sair
  end


  root 'posts#index'

  get 'profiles/show'
  
  get "adotar", to: 'posts#index', as: :adotar

  get "posts", to: 'posts#index'
  
  get "/pages/:page" => "pages#show"

  get '/:id', to: 'profiles#show', as: :id do
    resources :conversations
  end

  resources :conversations do
    resources :messages
  end

end

app/views/pages/ajuda.html.erb
<div class="col-md-3">

<div class="jumbotron" data-spy="affix" id="salve2">
<h6 style="color=#444; padding:0; padding-left:3px;"><strong>INÍCIO</strong></h6>
<button onclick="location.href='<%= adotar_path %>';" type="submit" class="btn btn-block btn-default " id="msg2"><i class="fa fa-paw" id="i"></i> Adotar</button>
<button onclick="location.href='/pages/ajuda';" type="submit" class="btn btn-block btn-default  active" id="msg2"><i class="fa fa-info-circle" id="i3"></i> Preciso de ajuda</button>
<button onclick="location.href='/pages/contato';" type="submit" class="btn btn-block btn-default " id="msg2"><i class="fa fa-phone" id="i"></i> Contato</button>
<h6 style="color=#444; padding:0; padding-left:3px;"><strong>TERMOS</strong></h6>
<button onclick="location.href='/pages/termos2';" type="submit" class="btn  btn-block btn-default" id="msg2"><i class="fa fa-legal " id="i22"></i> Termos de Uso</button>
<button onclick="location.href='/pages/termos';" type="submit" class="btn  btn-block btn-default " id="msg2"><i class="fa fa-lock fa-lg" id="i2"></i> Política de Privac.</button>

</br>



</div>
</div>


<div class="col-md-9">



<div class="jumbotron" id="salve22" style="max-width:none;">
<h3><i class="fa fa-question-circle"></i> Duvidas frequentes:</h3>
<legend></legend>
<h5><strong><i class="fa fa-hand-o-right"></i> Preciso de uma conta para postar um animal no site?</strong></h5>
<h5>Sim, é necessário fazer um cadastro no site para utilizar todas funcionalidades. <a href="<%= cadastrar_path %>">Cadastre-se.</a></h5>
<legend></legend>
<h5><strong><i class="fa fa-hand-o-right"></i> Como divulgar um animal para doação?</strong></h5>
<h5>Clique em "Doar" no menu lateral ou em "Crie um post" no banner de dicas. (É necessário estar <a href="<%= entrar_path %>">logado</a> com a sua conta).<h5>
<legend></legend>
<h5><strong><i class="fa fa-hand-o-right"></i> Como divulgar um perdido?</strong></h5>
<h5>Clique em "Animais perdidos" e em seguina no banner de dicas: "Seu amigo escapou? Clique aqui". (É necessário estar <a href="<%= entrar_path %>">logado</a> com a sua conta).<h5>
<legend></legend>
<h5><strong><i class="fa fa-hand-o-right"></i> Como apagar ou editar uma postagem?</strong></h5>
<h5>Logue na sua conta, depois vá em "Meus animais" (Menu lateral) ou "Meu perfil" (Barra de navegação superior). Lá você terá botões para editar ou apagar uma de suas postagens. (Também é possível fazer isso diretamente da postagem, basta estar logado em sua conta).<h5>
<legend></legend>
<h5><strong><i class="fa fa-hand-o-right"></i> Como editar informações da minha conta?</strong></h5>
<h5>Logue na sua conta, depois vá em "Editar minha conta" (menu lateral) ou clique em <i class="fa fa-cog" id="i3"></i>, depois "Editar minha conta".<h5>
<legend></legend>
<h5><strong><i class="fa fa-hand-o-right"></i> Como ver minhas mensagens do chat?</strong></h5>
<h5>Clique em <i class="fa fa-comments" id="i"></i> na barra superior de navegação. (Em algumas vezes é necessário clicar novamente após ser redirecionado).<h5>
<legend></legend>
<h5><strong><i class="fa fa-hand-o-right"></i> Encontrepet.com resgata animais e/ou disponibiliza abrigo?</strong></h5>
<h5>Não. Encontrepet é uma plataforma para ajudar na divulgação de animais para adoação e animais perdidos. Não resgatamos animais e não disponibilizamos abrigos.</h5>
<legend></legend>

<h5><strong><i class="fa fa-hand-o-right"></i> Continua com alguma dúvida?</strong></h5>
<h5>Envie um email para: encontrepet.com@gmail.com, ou entre em contato pela <a href="https://www.facebook.com/118543718481622">página do facebook.</a></h5>
<legend></legend>
</div>

<div class="jumbotron" id="salve">
  <div id="comodoar">
    <h4><strong>Dica 1:</strong></h4>
  </div>
<div class="texto">
<div class="bs-example">
    <div class="row" id="papara">

          <a href="#" class="thumbnail-primary">
                  <div class="col-xs-6 col-md-3 sepa" id="sepa">

          <h2 id="numeral"><strong>1</strong></h2>
          <img src="/primeiro1.png">
          <h4><strong id="entrar5">Resgate</strong></h4>
          <h5 id="entrar4">Salve um animal que esteja abandonado</h5>
           </div>
          </a>
      
          <a href="<%= cadastrar_path %>" class="thumbnail-primary">
                  <div class="col-xs-6 col-md-3 sepa" id="sepa">

            <h2 id="numeral"><strong>2</strong></h2>
          <img src="/segundo2.png">
          <h4><strong id="entrar5">Cadastre-se</strong></h4>
          <h5 id="entrar4">Faça seu cadastro no Encontrepet.com</h5>
           </div>
          </a>
    
          <a href="<%= new_post_path %>" class="thumbnail-primary">
                  <div class="col-xs-6 col-md-3 sepa" id="sepa">

            <h2 id="numeral"><strong>3</strong></h2>
          <img src="/terceiro2.png" >
          <h4><strong id="entrar5">Crie um post</strong></h4>
          <h5 id="entrar4">Envie uma foto do animal e preencha a sua ficha</h5>
           </div>
          </a>
   
  
          <a href="#" class="thumbnail-primary">
                <div class="col-xs-6 col-md-3 sepa" id="sepa">
            <h2 id="numeral"><strong>4</strong></h2>
          <img src="/quarto3.png">
          <h4><strong id="entrar5">Final feliz</strong></h4>
          <h5 id="entrar4">Aguarde e seu amigo vai encontrar uma nova família</h5>
           </div>
          </a>
     

    </div>
  </div>


</div>
  </div>



<div class="jumbotron" id="salve">
  <div id="comodoar">
    <h4><strong>Dica 2:</strong></h4>
  </div>
  
<a href="<%= new_lost_path %>"><img id="fala" src="/FALA3.png"></a>
  </div>

</div>
</br>
</br>
</br>
</br>
</br>
</br>

app/views/pages/bemvindo.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Encontrepet.com | Bem Vindo !</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag '//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <meta name="viewport" content="width=device-width,initial-scale=1">
  <style type="text/css">.tk-proxima-nova-soft{font-family:"proxima-nova-soft",sans-serif;}</style>
  <link rel="stylesheet" href="https://use.typekit.net/c/13b6dc/1w;proxima-nova-soft,7cdcb44be4a7db8877ffa5c0007b8dd865b3bbc383831fe2ea177f62257a9191,S2w:R:n4,S2x:R:n5,S2z:R:n7/d?3bb2a6e53c9684ffdc9a9afe1d5b2a6262b4be0bfc491ced4e51babf61457bcd45c064abb11f4930474791aa81bb8f532e58b4705dd9037fa122e4d3ebe3044ef7307a3f87027dba40c9d27f6e9e9d582ae392d45835bb" media="all">
  <style>
  body {
    background-color: #43c8c3;
    color: #2E2F30;
   
    margin: 0;
    font-family: "proxima-nova-soft", "proxima-nova", Helvetica, Arial, sans-serif;
    color: #3C545F;
    text-align: center;
  }

  #a {
padding: 30px;

  }

  #b {
  	padding-bottom: 20px;
  	padding-top: 0;
  	font-size: 20px;
  }

  #c {
  	padding-top:20px;
  	max-width: 100%;
  	display: block;
  	margin: 0 auto;
  }

  #d {
  	float: left;
  	max-width: 10%;
  }

  
  </style>

</head>

<body>


<img id="c" src="/encontrepet.png">


<div id="a">
<h1>BEM VINDO!</h1>
<h5 id="b">Encontrepet.com é uma simples rede social que facilita a adoção de animais que precisam de uma família.</h5>
<a href="<%= adotar_path %>" class="btn btn-success btn-lg">Continuar</a>
</br>

</br>
<div class="jumbotron" id="ficarmenor">
<h5>Usuários cadastrados:</h5>
<% @users.each do |user| %>
<h4><%= user.first_name %> <%= user.last_name %></h4>
<% end %>
</div>

</div>


</body>
</html>

app/views/pages/campanhas.html.erb
<div class="col-md-3">

<div class="jumbotron" data-spy="affix" id="salve2">
<h6 style="color=#4
}44; padding:0; padding-left:3px;"><strong>PÁGINAS</strong></h6>
<button onclick="location.href='<%= adotar_path %>';" type="submit" class="btn btn-block btn-default" id="msg2"><i class="fa fa-paw" id="i"></i> Adotar</button>
<button onclick="location.href='<%= losts_path %>';" type="submit" class="btn  btn-block btn-default" id="msg2"><i class="fa fa-search" id="i3"></i> Animais perdidos</button>
<button onclick="location.href='<%= new_post_path %>';" type="submit" class="btn  btn-block btn-default" id="msg2"><i class="fa fa-tag " id="i2"></i> Doar</button>
<button onclick="location.href='/pages/campanhas';" type="submit" class="btn  btn-block btn-default active" id="msg2"><i class="fa fa-usd" id="i1"></i> Campanhas <span class="label label-warning">Breve</span></button>

<% if user_signed_in? %>
<h6 style="color=#444; padding:0; padding-left:3px;"><strong>CONTA</strong></h6>
<button onclick="location.href='<%= id_path(current_user.profile_name) %>';" type="submit" class="btn btn-block btn-default" id="msg2"><i class="fa fa-user" id="i"></i> Meu perfil</button>
<button onclick="location.href='#';" type="submit" class="btn btn-block btn-default" id="msg2"  data-toggle="modal" data-target="#myModal2"><i class="fa fa-envelope" id="i22"></i> Mensagens</button>
<button onclick="location.href='<%= edit_user_registration_path %>';" type="submit" class="btn  btn-block btn-default" id="msg2"><i class="fa fa-cog" id="i"></i> Editar minha conta</button>
<button onclick="location.href='<%= sair_path %>';" type="submit" class="btn  btn-block btn-default" id="msg2"><i class="fa fa-sign-out" id="i3"></i> Sair</button>

<h6>Logado como <%= current_user.name %></h6>


<% else %>

<div id="ladoentrar2">
  <div class="actions">
    <button onclick="location.href='<%= entrar_path %>';" type="submit" class="btn btn-success btn-block btn-primary" id="msg">Entrar</button>
  </div>
</div>


<div id="ladoentrar">
<%= simple_form_for(:user, :defaults => { :input_html => { :class => "form-control" } }, as: resource_name, url: session_path(:user)) do |f| %>
 

 <%= f.input :email, label: false, :placeholder => "seu@email.com" %>
 <%= f.input :password, label: false, :placeholder => "senha" %>
  <div class="actions">
    <button type="submit" class="btn btn-success btn-block btn-primary" id="msg">Entrar</button>
  </div>
</div>

<% end %>
<% end %>

<h6 style="text-align:center;"><a href="/pages/ajuda">Dúvidas</a> | <a href="/pages/contato">Contato</a> | <a href="/pages/termos2">Termos</a></h6>





</div>
</div>

<div class="col-md-9">



<div class="jumbotron" id="salve22" style="max-width:none;">
<h2><img src="/encontrepet2.png" style="max-width: 150px;padding-bottom:0;margin-bottom:15px;">
<strong>+  </strong><i class="fa fa-usd" id="i1"></i> Campanhas</h2>
<legend></legend>
<h4>Você poderá <strong>criar campanhas</strong> para arrecadar doações e financiar <strong>uma boa causa</strong> como:</br></br> Verbas para construção de um abrigo, custear despesas médicas de um animal ou então arrecadar dinheiro para comprar ração para animais abandonados.</h4>
</br>
<h4><strong>Aguarde</strong>, iremos postar mais novidades sobre o novo sistema de campanhas.</h4>

</br>
<div style="padding:15px 0;border-radius:0;margin:0;" data-href="http://facebook.com/encontrepet" id="entrarfb" class="fb-like" data-layout="button_count" data-action="like" data-show-faces="true" data-share="true"></div>
</div>


<h5 id="entrar"><strong>Em breve no Encontrepet.com, feito com <i class="fa fa-heart" style="color:#FF3030;"></i> para os animais.</strong></h5>
</div>

</br>
</br>
</br>
</br>
</br>
</br>

app/views/pages/coisasuteis.html.erb
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
RAILS_ENV=production rackup private_pub.ru -s thin -E production</br>
</br>
ps aux | grep ruby</br>
kill -9 6076</br>

app/views/pages/colaboradores.html.erb
<div class="jumbotron" id="ficarmenor" style="text-align:center;border:4px solid #FF6600;border-radius:5px;">
</br>
	<img src="/encontrepet.png">
	<h3><strong>Desenvolvedor</strong></h3>
	<h4>Rafael Benaion</h4>
	<h3><strong>Colaboradores</strong></h3>
	<h4>Vítor Lima, 
  Ieda Ferreira Trindade, 
  Natalie Unterstell, 
  Lamonielly Romero, 
  Tamara Loewenstein, 
  Rafael Carvalho de Araujo.</h4>

  </br>

</div>
</br>

app/views/pages/contato.html.erb
<div class="col-md-3">

<div class="jumbotron" data-spy="affix" id="salve2">
<h6 style="color=#444; padding:0; padding-left:3px;"><strong>INÍCIO</strong></h6>
<button onclick="location.href='<%= adotar_path %>';" type="submit" class="btn btn-block btn-default " id="msg2"><i class="fa fa-paw" id="i"></i> Adotar</button>
<button onclick="location.href='/pages/ajuda';" type="submit" class="btn btn-block btn-default" id="msg2"><i class="fa fa-info-circle" id="i3"></i> Preciso de ajuda</button>
<button onclick="location.href='/pages/contato';" type="submit" class="btn btn-block btn-default   active " id="msg2"><i class="fa fa-phone" id="i"></i> Contato</button>
<h6 style="color=#444; padding:0; padding-left:3px;"><strong>TERMOS</strong></h6>
<button onclick="location.href='/pages/termos2';" type="submit" class="btn  btn-block btn-default" id="msg2"><i class="fa fa-legal " id="i22"></i> Termos de Uso</button>
<button onclick="location.href='/pages/termos';" type="submit" class="btn  btn-block btn-default " id="msg2"><i class="fa fa-lock fa-lg" id="i2"></i> Política de Privac.</button>

</br>


</div>
</div>


<div class="col-md-9">



<div class="jumbotron" id="salve22" style="max-width:none;">
<h3>Quer entrar em contato?</h3>
<legend></legend>
<h4>Envie um email para: <strong>encontrepet.com@gmail.com</strong></h4>
<h4>ou fale conosco pela nossa <a href="https://www.facebook.com/118543718481622">página do facebook</a>.</h4>
</div>
<h5 id="entrar"><strong>Encontrepet.com é de Curitiba, feito com <i class="fa fa-heart" style="color:#FF3030;"></i> para os animais.</strong></h5>
</div>

</br>
</br>
</br>
</br>
</br>
</br>

app/views/pages/senha.html.erb
<p>Hello <%= @resource.email %>!</p>

<p>Someone has requested a link to change your password. You can do this through the link below.</p>

<p><%= link_to 'Change my password', edit_password_url(@resource, reset_password_token: @token) %></p>

<p>If you didn't request this, please ignore this email.</p>
<p>Your password won't change until you access the link above and create a new one.</p>

app/views/pages/termos.html.erb
<div class="col-md-3">

<div class="jumbotron" data-spy="affix" id="salve2">
<h6 style="color=#444; padding:0; padding-left:3px;"><strong>INÍCIO</strong></h6>
<button onclick="location.href='<%= adotar_path %>';" type="submit" class="btn btn-block btn-default " id="msg2"><i class="fa fa-paw" id="i"></i> Adotar</button>
<button onclick="location.href='/pages/ajuda';" type="submit" class="btn btn-block btn-default " id="msg2"><i class="fa fa-info-circle" id="i3"></i> Preciso de ajuda</button>
<button onclick="location.href='/pages/contato';" type="submit" class="btn btn-block btn-default " id="msg2"><i class="fa fa-phone" id="i"></i> Contato</button>
<h6 style="color=#444; padding:0; padding-left:3px;"><strong>TERMOS</strong></h6>
<button onclick="location.href='/pages/termos2';" type="submit" class="btn  btn-block btn-default" id="msg2"><i class="fa fa-legal " id="i22"></i> Termos de Uso</button>
<button onclick="location.href='/pages/termos';" type="submit" class="btn  btn-block btn-default active" id="msg2"><i class="fa fa-lock fa-lg" id="i2"></i> Política de Privac.</button>

</br>


</div>
</div>


<div class="col-md-9">

<div class="jumbotron" id="ficarmenor5">
<h3><strong>Encontrepet.com Private Policy</strong><br></h3>
<br>
This privacy policy has been compiled to better serve those who are concerned with how their 'Personally identifiable information' (PII) is being used online. PII, as used in US privacy law and information security, is information that can be used on its own or with other information to identify, contact, or locate a single person, or to identify an individual in context. Please read our privacy policy carefully to get a clear understanding of how we collect, use, protect or otherwise handle your Personally Identifiable Information in accordance with our website.<br>
<br>
<strong>What personal information do we collect from the people that visit our blog, website or app?<br></strong>
<br>
When ordering or registering on our site, as appropriate, you may be asked to enter your name, email address, phone number or other details to help you with your experience.<br>
<br>
<strong>When do we collect information?<br></strong>
<br>
We collect information from you when you register on our site, fill out a form or enter information on our site.<br>
<br>
<br>
<strong>How do we use your information?<br></strong>
<br>
We may use the information we collect from you when you register, make a purchase, sign up for our newsletter, respond to a survey or marketing communication, surf the website, or use certain other site features in the following ways:<br>
<br>
      • To personalize user's experience and to allow us to deliver the type of content and product offerings in which you are most interested.<br>
      • To improve our website in order to better serve you.<br>
      • To allow us to better service you in responding to your customer service requests.<br>
<br>
<strong>How do we protect visitor information?<br></strong>
<br>
We do not use vulnerability scanning and/or scanning to PCI standards.<br>
We do not use Malware Scanning.<br>
<br>
<strong>We do not use an SSL certificate<br></strong>
<br>
<strong>Do we use 'cookies'?<br></strong>
<br>
We do not use cookies for tracking purposes<br>
<br>
You can choose to have your computer warn you each time a cookie is being sent, or you can choose to turn off all cookies. You do this through your <br>browser (like Internet Explorer) settings. Each browser is a little different, so look at your browser's Help menu to learn the correct way to modify <br>your cookies.<br>
<br>
If you disable cookies off, some features will be disabled that make your site experience more efficient and some of our services will not function <br>properly.<br>
<br>
However, you can still place orders .<br>
<br>
<br>
<strong>Third Party Disclosure<br></strong>
<br>
We do not sell, trade, or otherwise transfer to outside parties your personally identifiable information unless we provide you with advance notice. This does not include website hosting partners and other parties who assist us in operating our website, conducting our business, or servicing you, so long as those parties agree to keep this information confidential. We may also release your information when we believe release is appropriate to comply with the law, enforce our site policies, or protect ours or others' rights, property, or safety. <br>
<br>
However, non-personally identifiable visitor information may be provided to other parties for marketing, advertising, or other uses.<br>
<br>
<strong>Third party links<br></strong>
<br>
Occasionally, at our discretion, we may include or offer third party products or services on our website. These third party sites have separate and independent privacy policies. We therefore have no responsibility or liability for the content and activities of these linked sites. Nonetheless, we seek to protect the integrity of our site and welcome any feedback about these sites.
<br>
<strong>Google<br></strong>
<br>
Google's advertising requirements can be summed up by Google's Advertising Principles. They are put in place to provide a positive experience for users. https://support.google.com/adwordspolicy/answer/1316548?hl=en <br>
<br>
We use Google AdSense Advertising on our website.<br>
<br>
Google, as a third party vendor, uses cookies to serve ads on our site. Google's use of the DART cookie enables it to serve ads to our users based on their visit to our site and other sites on the Internet. Users may opt out of the use of the DART cookie by visiting the Google ad and content network privacy policy.<br>
<br>
We have implemented the following:<br>
      • Remarketing with Google AdSense<br>
      • Google Display Network Impression Reporting<br>
      • Demographics and Interests Reporting<br>
<br>
We along with third-party vendors, such as Google use first-party cookies (such as the Google Analytics cookies) and third-party cookies (such as the DoubleClick cookie) or other third-party identifiers together to compile data regarding user interactions with ad impressions, and other ad service functions as they relate to our website.<br>
<br>
Opting out:<br>
Users can set preferences for how Google advertises to you using the Google Ad Settings page. Alternatively, you can opt out by visiting the Network Advertising initiative opt out page or permanently using the Google Analytics Opt Out Browser add on.
<br>
<strong>California Online Privacy Protection Act<br></strong>
<br>
CalOPPA is the first state law in the nation to require commercial websites and online services to post a privacy policy. The law's reach stretches well beyond California to require a person or company in the United States (and conceivably the world) that operates websites collecting personally identifiable information from California consumers to post a conspicuous privacy policy on its website stating exactly the information being collected and those individuals with whom it is being shared, and to comply with this policy. - See more at: http://consumercal.org/california-online-privacy-protection-act-caloppa/#sthash.0FdRbT51.dpuf<br>
<br>
According to CalOPPA we agree to the following:<br>
Users can visit our site anonymously<br>
Once this privacy policy is created, we will add a link to it on our home page, or as a minimum on the first significant page after entering our website.
Our Privacy Policy link includes the word 'Privacy', and can be easily be found on the page specified above.<br>
<br>
Users will be notified of any privacy policy changes:<br>
      • On our Privacy Policy Page<br>
Users are able to change their personal information:<br>
      • By logging in to their account<br>
<br>
<strong>How does our site handle do not track signals?<br></strong>
We honor do not track signals and do not track, plant cookies, or use advertising when a Do Not Track (DNT) browser mechanism is in place.<br>
<br>
Does our site allow third party behavioral tracking?<br>
It's also important to note that we allow third party behavioral tracking<br>
<br>
<strong>COPPA (Children Online Privacy Protection Act)<br></strong>
<br>
When it comes to the collection of personal information from children under 13, the Children's Online Privacy Protection Act (COPPA) puts parents in control. The Federal Trade Commission, the nation's consumer protection agency, enforces the COPPA Rule, which spells out what operators of websites and online services must do to protect children's privacy and safety online.<br>
<br>
<strong>We do not specifically market to children under 13.<br></strong>
<br>
<strong> Information Practices<br></strong>
<br>
The Fair Information Practices Principles form the backbone of privacy law in the United States and the concepts they include have played a significant role in the development of data protection laws around the globe. Understanding the Fair Information Practice Principles and how they should be implemented is critical to comply with the various privacy laws that protect personal information.<br>
<br>
In order to be in line with Fair Information Practices we will take the following responsive action, should a data breach occur:<br>
We will notify the users via in site notification<br>
      • Within 7 business days<br>
<br>
We also agree to the individual redress principle, which requires that individuals have a right to pursue legally enforceable rights against data <br>collectors and processors who fail to adhere to the law. This principle requires not only that individuals have enforceable rights against data users,<br> but also that individuals have recourse to courts or a government agency to investigate and/or prosecute non-compliance by data processors.<br>
<br>
<strong>CAN SPAM Act<br></strong>
<br>
The CAN-SPAM Act is a law that sets the rules for commercial email, establishes requirements for commercial messages, gives recipients the right to have emails stopped from being sent to them, and spells out tough penalties for violations.<br>
<br>
<strong>We collect your email address in order to:<br></strong>
<br>
To be in accordance with CANSPAM we agree to the following:<br>
<br>
If at any time you would like to unsubscribe from receiving future emails, you can email us at<br>
and we will promptly remove you from ALL correspondence.<br>
<br>
<br>
<strong>Contacting Us<br></strong>
<br>
If there are any questions regarding this privacy policy you may contact us using the information below.<br>
<br>
encontrepet.com<br>
Rua Deputado Antônio Lopes Júnior<br>
Curitiba, Paraná 82520-690<br>
Brasil<br>
encontrepet.com@gmail.com<br>
<br>
Last Edited on 2015-07-02</div>

</div>