config/routes.rb
Rails.application.routes.draw do
  

  resources :posts


  devise_for :users

  resources :losts do
    resources :conversations
  end

   resources :profiles do
    resources :conversations
  end


  devise_scope :user do 
    get "cadastrar", to: "devise/registrations#new", as: :cadastrar
  end

  devise_scope :user do 
    get "entrar", to: "devise/sessions#new", as: :entrar
  end

  devise_scope :user do 
    get "sair", to: "devise/sessions#destroy", as: :sair
  end


  root 'posts#index'

  get 'profiles/show'
  
  get "adotar", to: 'posts#index', as: :adotar

  get "posts", to: 'posts#index'
  
  get "/pages/:page" => "pages#show"

  get '/:id', to: 'profiles#show', as: :id do
    resources :conversations
  end

  resources :conversations do
    resources :messages
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
	
    #belongs_to :documentet
    #accepts_nested_attributes_for :documentet
    belongs_to :user 
   

  has_attached_file :image, :styles => {:thumb => "242x200#"}
  validates_attachment_content_type :image, content_type: %w(image/jpeg image/jpg image/png)


	  validates :name, presence: true
    validates :age, presence: true
    validates :animal, presence: true
    validates :gender, presence: true
    validates :size, presence: true
    validates :about, presence: true
    validates :user_id, presence: true
    validates :castrado, presence: true
    validates :vacinado, presence: true
    validates :cidade, presence: true
    validates :telefone, presence: true
    validates :image, :attachment_presence => true

      scope :cidade, -> (cidade) { where("cidade like ?", "#{cidade}%")}
      scope :animal, -> (animal) { where("animal like ?", "#{animal}%")}
      scope :gender, -> (gender) { where("gender like ?", "#{gender}%")}
      scope :starts_with, -> (name) { where("LOWER(name) like ?", "#{name.downcase}%")}
      scope :castrado, -> (castrado) { where("castrado like ?", "#{castrado}%")}
      scope :vacinado, -> (vacinado) { where("vacinado like ?", "#{vacinado}%")}
      scope :tamanho, -> (size) { where("size like ?", "#{size}%")}

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  

  # GET /posts
  # GET /posts.json
  def index
  if user_signed_in?
    @users = User.where.not("id = ?",current_user.id).order("created_at DESC")
    @conversations = Conversation.involving(current_user)
  end
  # @posts = Post.order('created_at desc').all 
  @posts = Post.where(nil).order("created_at DESC") # creates an anonymous scope
  filtering_params(params).each do |key, value|
  @posts = @posts.public_send(key, value) if value.present?
  end
end

def filtering_params(params)
  params.slice(:tamanho, :animal, :gender, :starts_with, :castrado, :vacinado, :cidade)
end
 

  # GET /posts/1
  # GET /posts/1.json
  def show
     @meta = { title: 'Meu nome é '+@post.name.downcase.capitalize+', me adote!', description: @post.about, image: 'http://encontrepet.com'+@post.image.url(:thumb), type: 'article' }
  end

  # GET /posts/new
  def new
    @post = current_user.posts.new
    
    #@post.build_documentet
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.new(post_params)
      if @post.save
        redirect_to @post, notice: 'Doação criada com sucesso.'
      else
        render :new
      end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    @post = current_user.posts.find(params[:id])
    if params[:post] && params[:post].has_key?(:user_id)
      params[:post].delete(:user_id)
    end 
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Doação editada com sucesso.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    redirect_to posts_url, notice: 'Doação deletada com sucesso.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:image, :search_query, :sorted_by, :with_country_id, :with_created_at_gte, :celular, :telefone, :castrado, :vacinado, :cidade, :user_id, :name, :age, :animal, :gender, :size, :about, :image_file_name, :image_fields, :build_image, :remove_image)
    end
end

app/helpers/posts_helper.rb
module PostsHelper

  def conversation_interlocutor(conversation)
    conversation.recipient == current_user ? conversation.sender : conversation.recipient
  end


end

app/views/posts/_form.html.erb
<div class="jumbotron" id="ficarmenor2">	
<%= simple_form_for(@post, html: {multipart: true}) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
   
    </div>
  <% end %>

<h3 id="entrar2">Ficha do animal</h3>
</br >

<%= f.input :name, label: "Nome do animal:" %>

<%= f.input :age, label: "Idade :", placeholder: 'Exemplo: 5 meses'  %>

<%= f.input :animal, label: "Animal :", :as => :select, :collection => [['Cachorro', :Cachorro], ['Gato', :Gato], ['Outro', :Outro]]  %>

<%= f.input :gender, :as => :select, :collection => [['Macho', :Macho], ['Fêmea', :Fêmea]], label: "Gênero :" %>

<%= f.input :size, label: "Tamanho :", :as => :select, :collection => [['Pequeno', :Pequeno], ['Médio', :Médio], ['Grande', :Grande]]  %>

<%= f.input :castrado, label: "Castrado :", :as => :select, :collection => [['Sim', :Sim], ['Não', :Não]]  %>

<%= f.input :vacinado, label: "Vacinado :", :as => :select, :collection => [['Sim', :Sim], ['Não', :Não]]  %>

<%= f.input :about,label: "Descrição :", input_html: { rows: 4, class: 'input-xxlarge'}, placeholder: 'Escreva informações sobre o animal como cor, seu comportamento, onde foi encontrado e se foi desverminado.'  %>

<div class="well">
<%= f.input :image, as: :file, label: "Foto do animal :" %>
</div>


<h3 id="entrar2">Informações do doador</h3>
</br >

<%= f.input :cidade, label: "Cidade :", placeholder: 'Cidade e Estado', :as => :select, :collection => [['Curitiba - PR', :'Curitiba - PR'],

['Alagoas – Maceió', :'Alagoas – Maceió'],
['Amapá – Macapá', :'Amapá – Macapá'],
['Amazonas – Manaus', :'Amazonas – Manaus'],
['Bahia – Salvador', :'Bahia – Salvador'],
['Ceará – Fortaleza', :'Ceará – Fortaleza'],
['Distrito Federal – Brasília', :'Distrito Federal – Brasília'],
['Espírito Santo – Vitória', :'Espírito Santo – Vitória'],
['Goiás – Goiânia', :'Goiás – Goiânia'],
['Maranhão – São Luís', :'Maranhão – São Luís'],
['Mato Grosso – Cuiabá', :'Mato Grosso – Cuiabá'],
['Mato Grosso do Sul – Campo Grande', :'Mato Grosso do Sul – Campo Grande'],
['Minas Gerais – Belo Horizonte', :'Minas Gerais – Belo Horizonte'],
['Pará – Belém', :'Pará – Belém'],
['Paraíba – João Pessoa', :'Paraíba – João Pessoa'],
['Pernambuco – Recife', :'Pernambuco – Recife'],
['Piauí – Teresina', :'Piauí – Teresina'],
['Roraima – Boa Vista', :'Roraima – Boa Vista'],
['Rondônia – Porto Velho', :'Rondônia – Porto Velho'],
['Rio de Janeiro – Rio de Janeiro', :'Rio de Janeiro – Rio de Janeiro'],
['Rio Grande do Norte – Natal', :'Rio Grande do Norte – Natal'],
['Rio Grande do Sul – Porto Alegre', :'Rio Grande do Sul – Porto Alegre'],
['Santa Catarina – Florianópolis', :'Santa Catarina – Florianópolis'],
['São Paulo – São Paulo', :'São Paulo – São Paulo'],
['Sergipe – Aracaju', :'Sergipe – Aracaju'],
['Tocantins – Palmas', :'Tocantins – Palmas']] %>




<%= f.input :telefone, label: "Tel 1 :", placeholder: '(DDD) 0000-0000'  %>

<%= f.input :celular, label: "Tel 2 :", placeholder: 'Opcional'  %>

<button type="submit" class="btn btn-success btn-lg btn-block" id="button" data-loading-text="Enviando..." autocomplete="off">Publicar</button>
<%= link_to 'Cancelar', posts_path, :class => "btn btn-default btn-block", data: { confirm: 'Você tem certeza ?' } %>



</div>
<% end %>

app/views/posts/edit.html.erb
<% if current_user.profile_name.to_str == @post.user.profile_name.to_str %>



<div class="jumbotron" id="ficarmenor2">	
<%= simple_form_for(@post, html: {multipart: true}) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
   
    </div>
  <% end %>

<h3 id="entrar2">Editar Publicação</h3>
</br >

<%= f.input :name, label: "Nome do animal:" %>

<%= f.input :age, label: "Idade :", placeholder: 'Exemplo: 5 meses'  %>

<%= f.input :animal, label: "Animal :", :as => :select, :collection => [['Cachorro', :Cachorro], ['Gato', :Gato], ['Outro', :Outro]]  %>

<%= f.input :gender, :as => :select, :collection => [['Macho', :Macho], ['Fêmea', :Fêmea]], label: "Gênero :" %>

<%= f.input :size, label: "Tamanho :", :as => :select, :collection => [['Pequeno', :Pequeno], ['Médio', :Médio], ['Grande', :Grande]]  %>

<%= f.input :castrado, label: "Castrado :", :as => :select, :collection => [['Sim', :Sim], ['Não', :Não]]  %>

<%= f.input :vacinado, label: "Vacinado :", :as => :select, :collection => [['Sim', :Sim], ['Não', :Não]]  %>

<%= f.input :about,label: "Descrição :", input_html: { rows: 4, class: 'input-xxlarge'}, placeholder: 'Escreva informações sobre o animal como cor, seu comportamento, onde foi encontrado e se foi desverminado.'  %>
<strong>Foto:</strong>
<%= image_tag @post.image.url(:thumb), :id => "foto_ficha" %>
<a class="btn btn-warning btn-xs btn-block" data-toggle="collapse" href="#collapseExample" aria-expanded="false" aria-controls="collapseExample">Clique para alterar a foto</a>
</br >
<div class="collapse" id="collapseExample">
<div class="well">
<%= f.input :image, as: :file, label: "Foto do animal :" %>
</div>
</div>
</br >


<legend></legend>
<h3 id="entrar2">Informações do doador</h3>
</br >

<%= f.input :cidade, label: "Cidade :", placeholder: 'Cidade e Estado', :as => :select, :collection => [['Curitiba - PR', :'Curitiba - PR'],

['Alagoas – Maceió', :'Alagoas – Maceió'],
['Amapá – Macapá', :'Amapá – Macapá'],
['Amazonas – Manaus', :'Amazonas – Manaus'],
['Bahia – Salvador', :'Bahia – Salvador'],
['Ceará – Fortaleza', :'Ceará – Fortaleza'],
['Distrito Federal – Brasília', :'Distrito Federal – Brasília'],
['Espírito Santo – Vitória', :'Espírito Santo – Vitória'],
['Goiás – Goiânia', :'Goiás – Goiânia'],
['Maranhão – São Luís', :'Maranhão – São Luís'],
['Mato Grosso – Cuiabá', :'Mato Grosso – Cuiabá'],
['Mato Grosso do Sul – Campo Grande', :'Mato Grosso do Sul – Campo Grande'],
['Minas Gerais – Belo Horizonte', :'Minas Gerais – Belo Horizonte'],
['Pará – Belém', :'Pará – Belém'],
['Paraíba – João Pessoa', :'Paraíba – João Pessoa'],
['Pernambuco – Recife', :'Pernambuco – Recife'],
['Piauí – Teresina', :'Piauí – Teresina'],
['Roraima – Boa Vista', :'Roraima – Boa Vista'],
['Rondônia – Porto Velho', :'Rondônia – Porto Velho'],
['Rio de Janeiro – Rio de Janeiro', :'Rio de Janeiro – Rio de Janeiro'],
['Rio Grande do Norte – Natal', :'Rio Grande do Norte – Natal'],
['Rio Grande do Sul – Porto Alegre', :'Rio Grande do Sul – Porto Alegre'],
['Santa Catarina – Florianópolis', :'Santa Catarina – Florianópolis'],
['São Paulo – São Paulo', :'São Paulo – São Paulo'],
['Sergipe – Aracaju', :'Sergipe – Aracaju'],
['Tocantins – Palmas', :'Tocantins – Palmas']] %>

<%= f.input :telefone, label: "Tel 1 :", placeholder: '(DDD) 0000-0000'  %>

<%= f.input :celular, label: "Tel 2 :", placeholder: 'Opcional'  %>

  <script>
  $(document).ready(function(){
  $('#button').button();

  $('#button').click(function() {
    $(this).button('loading');
  });  
});
</script>
<button type="submit" class="btn btn-success btn-lg btn-block" id="button" data-loading-text="Enviando..." autocomplete="off">Salvar edição</button>
<%= link_to 'Cancelar', posts_path, :class => "btn btn-default btn-block", data: { confirm: 'Você tem certeza ?' } %>


</div>
<% end %>

</fieldset>

<% else %>
<%= render :file => 'public/422.html' %>
<% end %>

app/views/posts/index.html.erb
<div class="col-md-3">

<div class="jumbotron" data-spy="affix" id="salve2">
<h6 style="color=#4
}44; padding:0; padding-left:3px;"><strong>PÁGINAS</strong></h6>
<button onclick="location.href='<%= adotar_path %>';" type="submit" class="btn btn-block btn-default active" id="msg2"><i class="fa fa-paw" id="i"></i> Adotar</button>
<button onclick="location.href='<%= losts_path %>';" type="submit" class="btn  btn-block btn-default" id="msg2"><i class="fa fa-search" id="i3"></i> Animais perdidos</button>
<button onclick="location.href='<%= new_post_path %>';" type="submit" class="btn  btn-block btn-default" id="msg2"><i class="fa fa-tag " id="i2"></i> Doar</button>
<button onclick="location.href='/pages/campanhas';" type="submit" class="btn  btn-block btn-default" id="msg2"><i class="fa fa-usd" id="i1"></i> Campanhas <span class="label label-warning">Breve</span></button>
<button onclick="location.href='/pages/campanhas';" type="submit" class="btn  btn-block btn-default" id="msg2"><i class="fa fa-globe" id="i2"></i> Eventos <span class="label label-warning">Breve</span></button>

<% if user_signed_in? %>
<h6 style="color=#444; padding:0; padding-left:3px;"><strong>CONTA</strong></h6>
<button onclick="location.href='<%= id_path(current_user.profile_name) %>';" type="submit" class="btn btn-block btn-default" id="msg2"><i class="fa fa-user" id="i"></i> Meu perfil</button>
<button onclick="location.href='#';" type="submit" class="btn btn-block btn-default" id="msg2"  data-toggle="modal" data-target="#myModal2"><i class="fa fa-envelope" id="i22"></i> Mensagens</button>
<button onclick="location.href='<%= edit_user_registration_path %>';" type="submit" class="btn  btn-block btn-default" id="msg2"><i class="fa fa-cog" id="i"></i> Editar minha conta</button>
<button onclick="location.href='<%= sair_path %>';" type="submit" class="btn  btn-block btn-default" id="msg2"><i class="fa fa-sign-out" id="i3"></i> Sair</button>

<h6>Logado como <%= current_user.name %></h6>


<% else %>

<div id="ladoentrar2">
  <div class="actions">
    <button onclick="location.href='<%= entrar_path %>';" type="submit" class="btn btn-success btn-block btn-primary" id="msg">Entrar</button>
  </div>
</div>


<div id="ladoentrar">
<%= simple_form_for(:user, :defaults => { :input_html => { :class => "form-control" } }, as: resource_name, url: session_path(:user)) do |f| %>
 

 <%= f.input :email, label: false, :placeholder => "seu@email.com" %>
 <%= f.input :password, label: false, :placeholder => "senha" %>
  <div class="actions">
    <button type="submit" class="btn btn-success btn-block btn-primary" id="msg">Entrar</button>
  </div>
</div>

<% end %>
<% end %>

<h6 style="text-align:center;"><a href="/pages/ajuda">Dúvidas</a> | <a href="/pages/contato">Contato</a> | <a href="/pages/termos2">Termos</a></h6>





</div>
</div>





<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-64755509-1', 'auto');
  ga('send', 'pageview');

</script>

<!-- Button trigger modal -->

<% if user_signed_in? %>
<!-- Modal -->
<div class="modal fade" id="myModal2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title" id="myModalLabel"><i class="fa fa-comments"></i> Mensagens <%= link_to "Atualizar", adotar_path, :method => :get, class: "btn btn-success btn-xs start-conversation" %></h3>
      </div>
      <div class="modal-body">
        
        <% if @conversations.any? %>
          <ul class="media-list">
            <% @conversations.each do |conversation| %>
                <li class="media">
                  <%= image_tag("/default.png", class: "media-object pull-left") %>
                  <div class="media-body">
                    <%= link_to "", conversation_path(conversation), class: "conversation", "data-cid" => conversation.id, "data-toggle" => "modal", "data-target" => "#myModal2" %>
                        <h4 class="media-heading"><%= conversation_interlocutor(conversation).name %></h4>
                        <p>> <%= conversation.messages.last.nil? ? "No messages" : truncate(conversation.messages.last.body, length: 45) %></p>
                  </div>
                  <legend></legend>
                </li>

            <% end %>
          </ul>
      <% else %>
          <p>Nenhuma mensagem encontrada.</p>
      <% end %>

      </div>
    </div>
  </div>
</div>

<% end %>



<div class="col-md-9">


<div class="jumbotron" id="salve">
  <div id="comodoar">
    <h4><strong>Dica:</strong></h4>
  </div>
<div class="texto">
<div class="bs-example">
    <div class="row" id="papara">

          <a href="#" class="thumbnail-primary">
                  <div class="col-xs-6 col-md-3 sepa" id="sepa">

          <h2 id="numeral"><strong>1</strong></h2>
          <img src="/primeiro1.png">
          <h4><strong id="entrar5">Resgate</strong></h4>
          <h5 id="entrar4">Salve um animal que esteja abandonado</h5>
           </div>
          </a>
      
          <a href="<%= cadastrar_path %>" class="thumbnail-primary">
                  <div class="col-xs-6 col-md-3 sepa" id="sepa">

            <h2 id="numeral"><strong>2</strong></h2>
          <img src="/segundo2.png">
          <h4><strong id="entrar5">Cadastre-se</strong></h4>
          <h5 id="entrar4">Faça seu cadastro no Encontrepet.com</h5>
           </div>
          </a>
    
          <a href="<%= new_post_path %>" class="thumbnail-primary">
                  <div class="col-xs-6 col-md-3 sepa" id="sepa">

            <h2 id="numeral"><strong>3</strong></h2>
          <img src="/terceiro2.png" >
          <h4><strong id="entrar5">Crie um post</strong></h4>
          <h5 id="entrar4">Envie foto do animal, preencha a ficha</h5>
           </div>
          </a>
   
  
          <a href="#" class="thumbnail-primary">
                <div class="col-xs-6 col-md-3 sepa" id="sepa">
            <h2 id="numeral"><strong>4</strong></h2>
          <img src="/quarto3.png">
          <h4><strong id="entrar5">Final feliz</strong></h4>
          <h5 id="entrar4">Seu amigo vai encontrar uma família</h5>
           </div>
          </a>
     

    </div>
  </div>


</div>
  </div>




<div id="mostrarfiltro">
<a type="button" class="btn btn-primary" data-toggle="collapse" href="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
  <i class="fa fa-filter"></i>  Filtros
</a><strong>Selecionar opções de filtros.</strong>
</div>

<div class="collapse" id="collapseExample">
<div id="filtro">
<%= simple_form_for :post, :method => 'get', :url => "/", :html => {:class => 'form-inline'} do |f| %>

<%= f.input :cidade, input_html: { name: 'cidade', :value => params[:cidade] }, label: ('Cidade:  '), :required => false, :as => :select, :collection => [['Todas', :''], ['Curitiba - PR', :'Curitiba - PR'],
['Alagoas – Maceió', :'Alagoas – Maceió'],
['Amapá – Macapá', :'Amapá – Macapá'],
['Amazonas – Manaus', :'Amazonas – Manaus'],
['Bahia – Salvador', :'Bahia – Salvador'],
['Ceará – Fortaleza', :'Ceará – Fortaleza'],
['Distrito Federal – Brasília', :'Distrito Federal – Brasília'],
['Espírito Santo – Vitória', :'Espírito Santo – Vitória'],
['Goiás – Goiânia', :'Goiás – Goiânia'],
['Maranhão – São Luís', :'Maranhão – São Luís'],
['Mato Grosso – Cuiabá', :'Mato Grosso – Cuiabá'],
['Mato Grosso do Sul – Campo Grande', :'Mato Grosso do Sul – Campo Grande'],
['Minas Gerais – Belo Horizonte', :'Minas Gerais – Belo Horizonte'],
['Pará – Belém', :'Pará – Belém'],
['Paraíba – João Pessoa', :'Paraíba – João Pessoa'],
['Pernambuco – Recife', :'Pernambuco – Recife'],
['Piauí – Teresina', :'Piauí – Teresina'],
['Roraima – Boa Vista', :'Roraima – Boa Vista'],
['Rondônia – Porto Velho', :'Rondônia – Porto Velho'],
['Rio de Janeiro – Rio de Janeiro', :'Rio de Janeiro – Rio de Janeiro'],
['Rio Grande do Norte – Natal', :'Rio Grande do Norte – Natal'],
['Rio Grande do Sul – Porto Alegre', :'Rio Grande do Sul – Porto Alegre'],
['Santa Catarina – Florianópolis', :'Santa Catarina – Florianópolis'],
['São Paulo – São Paulo', :'São Paulo – São Paulo'],
['Sergipe – Aracaju', :'Sergipe – Aracaju'],
['Tocantins – Palmas', :'Tocantins – Palmas']], selected: "" %>
<%= f.input :gender, input_html: { name: 'gender', :value => params[:gender] }, label: ('Gênero:  '), :required => false, :as => :select, :collection => [['Todos', :''], ['Macho', :Macho], ['Fêmea', :Fêmea]], selected: "" %>
<%= f.input :animal, input_html: { name: 'animal', :value => params[:animal] }, label: ('Animal:  '), :required => false, :as => :select, :collection => [['Todos', :''], ['Cachorro', :Cachorro], ['Gato', :Gato], ['Outro', :Outro]], selected: "" %>
<%= f.input :castrado, input_html: { name: 'castrado', :value => params[:castrado] }, label: ('Castrado:  '), :required => false, :as => :select, :collection => [['Todos', :''], ['Sim', :Sim], ['Não', :Não]], selected: "" %>
<%= f.input :vacinado, input_html: { name: 'vacinado', :value => params[:vacinado] }, label: ('Vacinado:  '), :required => false, :as => :select, :collection => [['Todos', :''], ['Sim', :Sim], ['Não', :Não]], selected: "" %>
<%= f.input :tamanho, input_html: { name: 'tamanho', :value => params[:tamanho] }, label: ('Tamanho:  '), :required => false, :as => :select, :collection => [['Todos', :''], ['Pequeno', :Pequeno], ['Médio', :Médio], ['Grande', :Grande]], selected: ""  %>

<button type="submit" class="btn btn-success">
  <i class="fa fa-filter"></i> Filtrar
</button>
</div>
</div>
<%end %>




<div id="cards">
<div class="row tabela">


 
<% @posts.each do |post| %>
   <div class="col-sm-6 col-md-4">


    <div class="thumbnail" id="animal">
      <h3 id="cabeçalho"><strong><%= post.name.downcase.capitalize %></strong></h3>
    
      <div id="adotar_botao">
      </div> 
      <h4><span style="border-radius:0;margin:0;background-color: transparent;color: #777;" class="label label-default"><%= post.animal %> • <%= post.gender %> • <%= post.size %></span></h4>

      <% if post.image %>
      <%= image_tag post.image.url(:thumb), onerror: "this.src='/default_photo.png'", :id => "foto_ficha2" %>
      <% end %>
      <p style="font-family:'proxima-nova-soft','proxima-nova',Helvetica,Arial,sans-serif;margin:0; color: #777;padding-bottom:15px;"><strong><%= post.about %></strong></p>
      <div style="padding:6px 0;border-radius:0;margin:0;" data-href="<%= post_path(post) %>" id="entrarfb" class="fb-like" data-layout="button_count" data-action="like" data-show-faces="true" data-share="true"></div>
         

          <% if user_signed_in? %>

     <div class="btn-group btn-group-justified" role="group" aria-label="...">
     <div class="btn-group" role="group" aria-label="...">
     <a style="border-left:none;"id="msg3" class="btn btn-default btn-block" href="<%= post_path(post) %>" ><i class="fa fa-eye fa-lg"></i> Ver</a>
     </div>
     <div class="btn-group" role="group" aria-label="...">
     <a id="msg3" data-tooltip="tooltip" data-placement="bottom" title="Enviar mensagem" href="" data-sid="<%= current_user.id %>", data-rip="<%= post.user.id %>" class="btn btn-default btn-block start-conversation"><i class="fa fa-comments"></i> Chat</a>
      </div>
      </div>
    <% else %>
      <div class="btn-group btn-group-justified" role="group" aria-label="...">
      <div class="btn-group" role="group" aria-label="...">
      <a style="border-left:none;"id="msg3" class="btn btn-default btn-block" href="<%= post_path(post) %>" ><i class="fa fa-eye fa-lg"></i> Ver</a>
      </div>
      <div class="btn-group" role="group" aria-label="...">
     <a id="msg3" data-html="true" tabindex="0" class="btn btn-default btn-block start-conversation" role="button" data-toggle="popover" data-trigger="focus" title="Aviso!" data-content="Você precisa se <a href='<%= cadastrar_path %>'>Cadastrar</a> ou <a href='<%= entrar_path %>'>Logar</a> para usar o Chat." data-placement="bottom"><i class="fa fa-comments"></i> Chat</a>
        </div>
</div>
      <% end %>

   

</div>
 </div>
    <% end %>

 
</div>

<% if @posts.count == 0 %>
<div class="jumbotron" id="salve" style="background-color:#3CB4B0;border:none;">
  <h4 id="entrar2"><strong>Nenhum animal encontrado!</strong></h4>
<% end %>
</div>

</div>
</div>

app/views/posts/new.html.erb
<%= render 'form' %>